/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.3/samples
 */

plugins {
    java
}

repositories {
    mavenCentral()
}
tasks.test {
    useTestNG()

}
dependencies {
    implementation("com.codeborne:selenide:7.13.0")
    implementation("org.seleniumhq.selenium:selenium-java:4.39.0")
    testImplementation("org.testng:testng:7.11.0")
    implementation("org.apache.poi:poi:5.5.1")
    implementation("org.apache.poi:poi-ooxml:5.5.1")
    testImplementation("io.rest-assured:rest-assured:6.0.0")
    testImplementation("org.slf4j:slf4j-simple:2.0.17")
    implementation("com.aventstack:chaintest-testng:1.0.12")
    implementation("com.github.javafaker:javafaker:1.0.2") { exclude( module="snakeyaml" ) }
    implementation(group = "org.yaml", name = "snakeyaml", version = "1.17")

}



